package hfsguardadir.gui;

import hfsguardadir.comum.Rotinas;
import hfsguardadir.objetos.Diretorio;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

public class FrmInfoDiretorio extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

	public FrmInfoDiretorio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mudarLingua();
        
        tabelaInfo.getSelectionModel().setSelectionInterval(0, 0);

        DefaultTableCellRenderer r = new DefaultTableCellRenderer() {
            private static final long serialVersionUID = 1L;

			@Override
            public Component getTableCellRendererComponent(JTable table,
                    Object value, boolean isSelected, boolean hasFocus,
                    int row, int column) {
                super.getTableCellRendererComponent(table, value, 
                        isSelected, hasFocus, row, column);
                setFont(new java.awt.Font("Tahoma", 1, 11));
                return this;
            }
        };
        this.tabelaInfo.getColumnModel().getColumn(0).setCellRenderer(r);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLegenda = new javax.swing.JPanel();
        labArquivoComum = new javax.swing.JLabel();
        labArquivoOculto = new javax.swing.JLabel();
        labArquivoSistema = new javax.swing.JLabel();
        labLegendaDiretorio = new javax.swing.JLabel();
        labVolumeID = new javax.swing.JLabel();
        labArquivoSomenteLeitura = new javax.swing.JLabel();
        scrollTabelaInfo = new javax.swing.JScrollPane();
        tabelaInfo = new javax.swing.JTable();
        panelBotao = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("recursos/hfsguardadiretorio_pt"); // NOI18N
        setTitle(bundle.getString("FrmInfoDiretorio.titulo")); // NOI18N
        setModal(true);
        setResizable(false);

        panelLegenda.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("FrmInfoDiretorio.panelLegenda"))); // NOI18N
        panelLegenda.setLayout(new java.awt.GridLayout(3, 2));

        labArquivoComum.setText(bundle.getString("FrmInfoDiretorio.labArquivoComum")); // NOI18N
        panelLegenda.add(labArquivoComum);

        labArquivoOculto.setText(bundle.getString("FrmInfoDiretorio.labArquivoOculto")); // NOI18N
        panelLegenda.add(labArquivoOculto);

        labArquivoSistema.setText(bundle.getString("FrmInfoDiretorio.labArquivoSistema")); // NOI18N
        panelLegenda.add(labArquivoSistema);

        labLegendaDiretorio.setText(bundle.getString("FrmInfoDiretorio.labDiretorio")); // NOI18N
        panelLegenda.add(labLegendaDiretorio);

        labVolumeID.setText(bundle.getString("FrmInfoDiretorio.labVolumeID")); // NOI18N
        panelLegenda.add(labVolumeID);

        labArquivoSomenteLeitura.setText(bundle.getString("FrmInfoDiretorio.labArquivoSomenteLeitura")); // NOI18N
        panelLegenda.add(labArquivoSomenteLeitura);

        getContentPane().add(panelLegenda, java.awt.BorderLayout.NORTH);

        tabelaInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Aba:", null},
                {"Nome:", null},
                {"Tamanho:", null},
                {"Tipo:", null},
                {"Modificado:", null},
                {"Atributos:", null},
                {"Caminho:", null}
            },
            new String [] {
                "Item", "Descrição"
            }
        ) {
            private static final long serialVersionUID = 1L;
            
			Class<?>[] types = new Class<?>[] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class<?> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaInfo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollTabelaInfo.setViewportView(tabelaInfo);

        getContentPane().add(scrollTabelaInfo, java.awt.BorderLayout.CENTER);

        btnOk.setMnemonic('O');
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        panelBotao.add(btnOk);

        getContentPane().add(panelBotao, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(358, 312));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel labArquivoComum;
    private javax.swing.JLabel labArquivoOculto;
    private javax.swing.JLabel labArquivoSistema;
    private javax.swing.JLabel labArquivoSomenteLeitura;
    private javax.swing.JLabel labLegendaDiretorio;
    private javax.swing.JLabel labVolumeID;
    private javax.swing.JPanel panelBotao;
    private javax.swing.JPanel panelLegenda;
    private javax.swing.JScrollPane scrollTabelaInfo;
    private javax.swing.JTable tabelaInfo;
    // End of variables declaration//GEN-END:variables

    /**
     * @param diretorio the diretorio to set
     */
    public void setDiretorio(Diretorio diretorio) {
        if (diretorio!=null) {
            tabelaInfo.getModel().setValueAt(diretorio.getAba().getNome(), 0, 1);
            tabelaInfo.getModel().setValueAt(diretorio.getNome(), 1, 1);
            tabelaInfo.getModel().setValueAt(diretorio.getTamanhoFormatado(), 2, 1);
            tabelaInfo.getModel().setValueAt(diretorio.getTipo().getNome(), 3, 1);
            tabelaInfo.getModel().setValueAt(diretorio.getModificadoFormatado(), 4, 1);
            tabelaInfo.getModel().setValueAt(diretorio.getAtributos(), 5, 1);
            tabelaInfo.getModel().setValueAt(diretorio.getCaminho(), 6, 1);
            tabelaInfo.getColumnModel().getColumn(1).setPreferredWidth(
                    diretorio.getCaminho().length()*7);
        }
    }
   
    private void mudarLingua() {
	setTitle(Rotinas.getRecurso("FrmInfoDiretorio.titulo"));
        labArquivoComum.setText(Rotinas.getRecurso("FrmInfoDiretorio.labArquivoComum"));
        labArquivoOculto.setText(Rotinas.getRecurso("FrmInfoDiretorio.labArquivoOculto"));
        labArquivoSistema.setText(Rotinas.getRecurso("FrmInfoDiretorio.labArquivoSistema"));
        labLegendaDiretorio.setText(Rotinas.getRecurso("FrmInfoDiretorio.labDiretorio"));
        labVolumeID.setText(Rotinas.getRecurso("FrmInfoDiretorio.labVolumeID"));
        labArquivoSomenteLeitura.setText(
                Rotinas.getRecurso("FrmInfoDiretorio.labArquivoSomenteLeitura"));
        
        tabelaInfo.getColumnModel().getColumn(0).setHeaderValue(
                Rotinas.getRecurso("FrmInfoDiretorio.item"));
        tabelaInfo.getColumnModel().getColumn(1).setHeaderValue(
                Rotinas.getRecurso("FrmInfoDiretorio.descricao"));
        
        tabelaInfo.getModel().setValueAt(Rotinas.getRecurso("Tabela.aba")+":", 0, 0);
        tabelaInfo.getModel().setValueAt(Rotinas.getRecurso("Tabela.nome")+":", 1, 0);
        tabelaInfo.getModel().setValueAt(Rotinas.getRecurso("Tabela.tamanho")+":", 2, 0);
        tabelaInfo.getModel().setValueAt(Rotinas.getRecurso("Tabela.tipo")+":", 3, 0);
        tabelaInfo.getModel().setValueAt(Rotinas.getRecurso("Tabela.modificado")+":", 4, 0);
        tabelaInfo.getModel().setValueAt(Rotinas.getRecurso("Tabela.atributos")+":", 5, 0);
        tabelaInfo.getModel().setValueAt(Rotinas.getRecurso("Tabela.caminho")+":", 6, 0);        
    }    
}
